######################################################################
# Automatically generated by qmake (2.01a) Tue May 29 20:43:43 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += tcpclient.h
SOURCES += main.cpp tcpclient.cpp
TRANSLATIONS += tcpclient_zh.ts
QT += network

