######################################################################
# Automatically generated by qmake (2.01a) Tue May 29 20:42:14 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += server.h tcpclientsocket.h tcpserver.h
SOURCES += main.cpp server.cpp tcpclientsocket.cpp tcpserver.cpp
TRANSLATIONS += tcpserver_zh.ts
QT += network
